[toolchain]
anchor_version = "0.31.1"
solana_version = "2.3.0"

[provider]
cluster = "Localnet"
wallet  = "~/.config/solana/id.json"

[programs.localnet]
reward_pool = "5HfySyCkk6ApUJs658yAdtQBotQxNE3MxsA2MeLd4j5v"
